version: "3.7"
services:
  express: 
    container_name: express
    build:
      context: ./express
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      JWT_SECRET: secret
      MONGO_URL: mongodb://root:rootpassword@mongodb:27017
    volumes:
      - ./express:/usr/src/app
    ports:
      - 8080:8080
    networks:
      - default
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - default
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   environment:
  #     NODE_ENV: development
  #   volumes:
  #     - ./frontend/src:/usr/src/app/src
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - default
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - default
networks:
  default:
    driver: bridge
volumes:
  mongodb_data_container:
